version: '3'
# -----------------------------------------共享配置-----------------------------------
x-base-config:
  &base-config
  restart: always
  logging:
    driver: "json-file"
    options:
      max-size: "2m"
      max-file: "20"
  environment:
    TZ: Asia/Shanghai
# -----------------------------------------共享配置-----------------------------------

services:
  node:
    container_name: node
    image: node:21-alpine
    <<: *base-config
    working_dir: /app
    volumes:
      - .:/app:cached
    ports:
      - "4000:4000"
    # command: /bin/sh -c "npm install && npm run dev"
    stdin_open: true
    tty: true
